name: Deploy to Google Compute Engine

on:
  push:
    branches: [ "master" ]
    paths-ignore: [ 'README.md' ]
  pull_request:
    branches: [ master ]
    paths-ignore: [ 'README.md' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy files via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USERNAME }}
          key: ${{ secrets.GCP_SSH_KEY }}
          source: "."
          target: "/home/${{ secrets.GCP_USERNAME }}/app"
          rm: true 

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USERNAME }}
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
            set -e

            cd /home/${{ secrets.GCP_USERNAME }}/app/ml-inference-platform

            # Create/overwrite .env on the VM (in the same dir as docker-compose.yml)
            cat > .env << 'EOF'
            ${{ secrets.ENV_FILE }}
            EOF

            # (Optional) ensure correct permissions
            chmod 600 .env

            docker compose down --remove-orphans
            docker compose up -d --build 
            docker image prune -f
